---
- hosts: all
  become: yes
  tasks:
  - name: first template with dynamic
    template:
      src: first.j2
      dest: /home/ansible/first
  - name: second template task
    template:
      src: second.j2
      dest: /home/ansible/second